sonar.projectKey=EsnyE_python-project-50
sonar.organization=esnye
sonar.sources=gendiff
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
